# Generated by Django 4.2.1 on 2023-06-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_cliente_reservaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('precio', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.coordinador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservaServicio',
        ),
    ]
